[project]
name = "parking-by-tps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "bs4>=0.0.2",
    "crypto>=1.4.1",
    "cryptography>=45.0.7",
    "html5lib>=1.1",
    "lxml>=6.0.1",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "parkocr>=0.1.1",
    "pyautogui>=0.9.54",
    "pycrypto>=2.6.1",
    "pycryptodome>=3.23.0",
    "pydal>=20250906.1",
    "pydantic>=2.11.7",
    "pymysql>=1.1.2",
    "python-dotenv>=1.1.1",
    "ttkwidgets>=0.13.0",
]
